name: opennms-minion
base: core18
version: '25.1.1'
summary: OpenNMS Horizon Minion application for distributed monitoring
description: |
  OpenNMS Horizon is an enteprise grad open source network monitoring tool. The 
  Minion is the distributed network monitoring component allowing monitoring of
  isolated network areas which can't be reached from a central OpenNMS Horizon
  instance.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64
    run-on: amd64

apps:
  openms-minion:
    environment:
      JAVA_HOME: "$SNAP/usr/lib/jvm/java-11-openjdk-amd64"
    command: |
      opt/minion/bin/karaf server
    daemon: simple

parts:
  openjdk-11-jdk:
    plugin:  nil
    stage-packages:
    - ca-certificates-java
    - openjdk-11-jdk-headless
    override-build: |
      unlink $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk-amd64/lib/security/blacklisted.certs
      unlink $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts
      unlink $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk-amd64/lib/security/default.policy
      unlink $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk-amd64/lib/security/public_suffix_list.dat
      cp $SNAPCRAFT_PART_INSTALL/etc/java-11-openjdk/security/blacklisted.certs $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk-amd64/lib/security/blacklisted.certs
      cp $SNAPCRAFT_PART_INSTALL/etc/ssl/certs/java/cacerts $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts
      cp $SNAPCRAFT_PART_INSTALL/etc/java-11-openjdk/security/default.policy $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk-amd64/lib/security/default.policy
      cp $SNAPCRAFT_PART_INSTALL/etc/java-11-openjdk/security/public_suffix_list.dat $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk-amd64/lib/security/public_suffix_list.dat
      snapcraftctl set-version "$VERSION"
  opennms-minion:
    plugin: dump
    source: https://github.com/OpenNMS/opennms/releases/download/opennms-$SNAPCRAFT_PROJECT_VERSION-1/minion-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    #source: minion-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    organize:
      '*' : opt/minion
