name: opennms-minion
base: core18
version: '25.1.1'
summary: OpenNMS Horizon Minion application for distributed monitoring
description: |
  OpenNMS Horizon is an enteprise grad open source network monitoring tool. The 
  Minion is the distributed network monitoring component allowing monitoring of
  isolated network areas which can't be reached from a central OpenNMS Horizon
  instance.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64
    run-on: amd64

apps:
  openms-minion:
    environment:
      JAVA_HOME: "$SNAP/usr/lib/jvm/java-11-openjdk-amd64"
    command: |
      opt/minion/bin/karaf server
    daemon: simple

parts:
  openjdk-11-jdk:
    plugin:  nil
    stage-packages:
    - ca-certificates-java
    - openjdk-11-jdk-headless
  opennms-minion:
    plugin: dump
    source: https://github.com/OpenNMS/opennms/releases/download/opennms-$SNAPCRAFT_PROJECT_VERSION-1/minion-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    #source: minion-$SNAPCRAFT_PROJECT_VERSION.tar.gz
    organize:
      '*' : opt/minion
